plugins {
    id 'com.android.application'
}

android {
    namespace 'com.adsurge.mediation.sample'
    compileSdk Integer.parseInt(project.ANDROID_BUILD_SDK_VERSION)

    defaultConfig {
        applicationId "com.adsurge.mediation.demo"
        minSdk Integer.parseInt(project.ANDROID_BUILD_MIN_SDK_VERSION)
        targetSdk Integer.parseInt(project.ANDROID_BUILD_SDK_VERSION)
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.adsurge.sdk:mediation-sdk:1.8.0'
    implementation 'com.adsurge.sdk:adsurge-adapter:1.9.0.1'
    implementation 'com.adsurge.sdk:admob-adapter:25.4.0.1'
    implementation 'com.adsurge.sdk:applovin-adapter:13.6.3.1'
    implementation 'com.adsurge.sdk:bigo-adapter:5.10.1.1'
    implementation 'com.adsurge.sdk:inmobi-adapter:11.4.1.0'
    implementation 'com.adsurge.sdk:vungle-adapter:7.7.7.1'
    implementation 'com.adsurge.sdk:meta-adapter:6.21.0.3'
    implementation 'com.adsurge.sdk:mintegral-adapter:17.1.61.1'
    implementation 'com.adsurge.sdk:pangle-adapter:8.2.0.4.1'
}
